language: cpp
compiler:
- clang
- gcc
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install perceptualdiff
- sudo apt-get install imagemagick
- sudo apt-get install libosmesa6-dev
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script: mkdir bin && cd bin && cmake -DUSE_OS_MESA=ON ../test/batch && make && ./spirebatch
after_success:
- sudo apt-get --no-install-recommends install doxygen
- git clone https://github.com/iauns/travis-doxy-helper ./doxy-helper
- ./doxy-helper/update-doxygen.sh ./.dox ./dox-repo https://github.com/SCIInstitute/spire
branches:
  only:
  - master
  - dev
env:
  global:
    secure: Kj2jSPu0BR7oT31mW1AceYsEHOrTooiyIr3AA8bBpV2nObMcsbc0I33AzGH59fzcjwWOA6TW2LGzD+UknNI0JLNlgOCzsZ/M0i6q+BF/+X/Hsa+TO2z8qsXIA9lhzWBP51AT1KhsZuiEwqO6Mm9OV8jYUkqhX/f9Lale5LfhNh0=
