language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install perceptualdiff
  - sudo apt-get install imagemagick
  - sudo apt-get install libosmesa6-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

# For QT support:
# sudo apt-get install libqt4-dev qt4-qmake

script: mkdir bin && cd bin && cmake -DUSE_OS_MESA=ON ../test/batch && make && ./spirebatch
branches:
  only:
    - master
    - dev
